### ISSUE TITLE
Hotkey conflict

### ISSUE THREAD

**Issue by MisterSheeple** [craftycodie/MineOnline#297]
The MineOnline menu is mapped to R, which causes conflicts on classic versions where the Respawn hotkey is also mapped to R.

**Comment by robinuniverse** [comment]
You can change the mineonline menu hotkey in the settings

**Comment by craftycodie** [comment]
I was aware of this during implementation, but I couldn't find a more suitable key, and found myself rebinding the classic key since I was barely using it...
At this point I dont want to change the classic respawn key default but am open to the idea of changing the mineonline menu key default. That said, I can't think of a nicer button for it... 
Any ideas?

**Comment by MisterSheeple** [comment]
> I was aware of this during implementation, but I couldn't find a more suitable key, and found myself rebinding the classic key since I was barely using it...
> At this point I dont want to change the classic respawn key default but am open to the idea of changing the mineonline menu key default. That said, I can't think of a nicer button for it... 
> Any ideas?

Maybe a function key?

**Comment by craftycodie** [comment]
Not a bad idea I think there's one we use for the debug menu currently

**Comment by craftycodie** [comment]
Closed due to inactivity
